apiVersion: v1
kind: Service
metadata:
  name: mariadb
spec:
  type: NodePort
  ports:
    - nodePort: 30222
      port: 30222
      targetPort: 3306
      name: mariadb
  selector:
    app: mariadb

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: mariadb
spec:
  selector:
    matchLabels:
      app: mariadb
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mariadb
    spec:
      containers:
      - image: docker.io/library/mariadb:11.4
        name: mariadb
        ports:
        - containerPort: 3306
          name: mariadb
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "openlab"  # 직접 문자열로 지정
        - name: MYSQL_DATABASE
          value: "openlab"
        - name: MYSQL_USER
          value: "admin"
        - name: MYSQL_PASSWORD
          value: "openlab"
