apiVersion: apps/v1
kind: Deployment
metadata:
  name: task-msa-gateway
  labels:
    app: task-msa
spec:
  replicas: 1
  selector:
    matchLabels:
      app: task-msa
      tier: backend
  template:
    metadata:
      annotations:
        argocd-update-time: Fri Sep  6 00:44:28 UTC 2024
      labels:
        app: task-msa
        tier: backend
    spec:
      containers:
        - name: task-msa
          image: soyoung1122/task_msa_gateway:latest
          imagePullPolicy: Always
          resources:
            requests:
              memory: "256Mi"
              cpu: "50m"
            limits:
              memory: "1Gi"
              cpu: "500m"
          ports:
            - containerPort: 8083
          envFrom:
            - configMapRef:
                name: kpaas-msa-configmap
      imagePullSecrets:
        - name: dockerhub
