kind: Service
apiVersion: v1
metadata:
  name: task-msa-gateway
  labels:
    app: task-msa
    tier: backend
  namespace: default
spec:
  type: NodePort
  selector:
    app: task-msa
    tier: backend
  ports:
    - protocol: TCP
      port: 8083
      targetPort: 8083
      nodePort: 30012
      name: task-msa