apiVersion: v1
kind: ConfigMap
metadata:
  name: kpaas-msa-configmap
  namespace: task
data:
  MSA_API_URL: http://115.68.198.204:30010
  MSA_SD_API_URL: http://115.68.198.204:30014
  MSA_UI_URL: http://115.68.198.204:30011
  MSA_GATEWAY_URL: http://115.68.198.204:30012
  