apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    argocd-update-time: Fri Sep  6 06:51:16 UTC 2024
  name: spring-music
  labels:
    app: music
  namespace: task
spec:
  replicas: 1
  selector:
    matchLabels:
      app: music
  template:
    metadata:
      labels:
        app: music
    spec:
      containers:
        - name: spring-music
          image: soyoung1122/spring-music:latest
          imagePullPolicy: Always
          resources:
            requests:
              memory: "256Mi"
              cpu: "50m"
            limits:
              memory: "1Gi"
              cpu: "500m"
          ports:
            - containerPort: 8080
      imagePullSecrets:
        - name: dockerhub
