apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-music
  labels:
    app: music
  namespace: kps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: music
  template:
    metadata:
      annotations:
        argocd-update-time: Thu Oct 17 05:15:41 UTC 2024
      labels:
        app: music
    spec:
      containers:
        - name: spring-music
          image: kps-container-registry.ncr.gov-ntruss.com/spring-music:1.
          imagePullPolicy: Always
          resources:
            requests:
              memory: "256Mi"
              cpu: "50m"
            limits:
              memory: "1Gi"
              cpu: "500m"
          ports:
            - containerPort: 8080
      imagePullSecrets:
        - name: ncp-container
