kind: Service
apiVersion: v1
metadata:
  name: spring-music
  labels:
    app: music
spec:
  type: NodePort
  selector:
    app: music
  ports:
    - protocol: TCP
      port: 8085
      targetPort: 8080
      nodePort: 30015
      name: spring-music
