kind: Service
apiVersion: v1
metadata:
  name: task-msa-sd-api
  labels:
    app: task-msa
    tier: backend
  namespace: task
spec:
  type: NodePort
  selector:
    app: task-msa
    tier: backend
  ports:
    - protocol: TCP
      port: 8084
      targetPort: 8084
      nodePort: 30014
      name: task-msa