kind: Service
apiVersion: v1
metadata:
  name: task-msa-ui
  labels:
    app: task-msa
    tier: backend
  namespace: default
spec:
  type: NodePort
  selector:
    app: task-msa
    tier: backend
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
      nodePort: 30011
      name: task-msa