apiVersion: apps/v1
kind: Deployment
metadata:
  name: task_msa_api
  labels:
    app: task_msa
  namespace: task
spec:
  replicas: 1
  selector:
    matchLabels:
      app: task_msa
      tier: backend
  template:
    metadata:
      labels:
        app: task_msa
        tier: backend
    spec:
      containers:
        - name: task_msa
          image: soyoung1122/task_msa_api:latest
          imagePullPolicy: Always
          resources:
            requests:
              memory: "256Mi"
              cpu: "50m"
            limits:
              memory: "1Gi"
              cpu: "500m"
          ports:
            - containerPort: 8082
          envFrom:
            - configMapRef:
                name: kpaas-msa-configmap
      imagePullSecrets:
        - name: dockerhub