kind: Service
apiVersion: v1
metadata:
  name: task_msa_api
  labels:
    app: task_msa
    tier: backend
  namespace: task
spec:
  type: NodePort
  selector:
    app: task_msa
    tier: backend
  ports:
    - protocol: TCP
      port: 8082
      targetPort: 8082
      nodePort: 30010
      name: task_msa